version: '3'
services:
  db:
#    image: postgres:16.8-alpine3.21
    build:
      context: ./postgres
      target: postgres_with_script
    container_name: platform-repo
    restart: unless-stopped
    expose:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: '{$POSTGRES_USER}'
      POSTGRES_PASSWORD: '{$POSTGRES_PASSWORD}'
      POSTGRES_DB: '{$POSTGRES_DB}'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/platform_repo:/var/lib/postgresql/data/pgdata
    networks:
      - platform-network
#volumes:
  # certbot-etc:
#  wordpress:
#  platform-repo:
networks:
  platform-network:
    driver: bridge
